//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [Required]
        [StringLength(20)]
        public string Name { get; set; }
        [Required]
        [StringLength(2000)]
        public string Description { get; set; }
        [Required]
        [Range(1, 1000)]
        public int Quantity { get; set; }
        [Required]
        [Range(1,150)]
        public decimal Price { get; set; }
        public int ID { get; set; }
    }
}
